### ISSUE TITLE
Collect all Pets

### ISSUE THREAD

**Issue by magie123147** [jmesfo0/jmesfo0#2]
CAP Script not working? Keep getting 404 error.

**Comment by jmesfo0** [comment]
I deleted all my scripts

**Comment by magie123147** [comment]
Aww that sucks you were only one with good rebirth script

**Comment by jmesfo0** [comment]
ok i reuploaded it, enjoy, i didn't think many used it

**Comment by magie123147** [comment]
Thank you <3 yes I love it!! lol
